// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tesense.dpsintegration.service;

import java.lang.String;

privileged aspect Sensor_Roo_JavaBean {
    
    public String Sensor.getName() {
        return this.name;
    }
    
    public void Sensor.setName(String name) {
        this.name = name;
    }
    
}
